#!/usr/bin/env node
/* Renders the score and embeds it for the player.
 *   node tools/build_audio.cjs            -> src/score-audio.js (+ media/score.wav if --wav)
 * The score is code (src/score.js); this file is its build artifact, so the
 * player can start instantly instead of synthesising for tens of seconds.
 */
'use strict';
const fs = require('fs');
const path = require('path');
const os = require('os');
const { execFileSync } = require('child_process');
const { requirePlaywright, filmURL, findFFmpeg } = require('./lib.cjs');
const { renderWav } = require('./audio.cjs');

async function main() {
  const keepWav = process.argv.includes('--wav');
  const root = path.join(__dirname, '..');
  const { chromium } = requirePlaywright();
  const browser = await chromium.launch();
  const page = await browser.newPage();
  page.on('pageerror', (e) => console.error('[pageerror]', e.message));
  await page.goto(filmURL({ mode: 'still' }));
  await page.waitForFunction(() => window.FILM_READY && window.SCORE);
  const wav = await renderWav(page);
  await browser.close();

  const tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'cinq-'));
  const wavPath = keepWav ? path.join(root, 'media', 'score.wav') : path.join(tmp, 'score.wav');
  fs.mkdirSync(path.dirname(wavPath), { recursive: true });
  fs.writeFileSync(wavPath, wav);
  const mp3 = path.join(tmp, 'score.mp3');
  execFileSync(findFFmpeg(), ['-hide_banner', '-loglevel', 'error', '-y', '-i', wavPath, '-c:a', 'libmp3lame', '-b:a', '192k', '-write_xing', '1', mp3]);
  const b64 = fs.readFileSync(mp3).toString('base64');
  const out = path.join(root, 'src', 'score-audio.js');
  fs.writeFileSync(out, '// Generated by tools/build_audio.cjs from src/score.js - do not edit.\n' +
    `window.SCORE_AUDIO = { type: 'audio/mpeg', data: '${b64}' };\n`);
  console.log(`wrote ${out} (${(b64.length / 1e6).toFixed(2)} MB base64)` + (keepWav ? `, ${wavPath}` : ''));
}
main().catch((e) => { console.error(e); process.exit(1); });
