#!/usr/bin/env python3
"""Extract calligraphy glyph outlines as per-contour SVG paths (em units, y down).

The title characters are traced contour-by-contour in the animation, so each
closed contour is emitted as its own path string together with the glyph's
advance and ink bounding box.

usage: extract_glyphs.py FONT CHARS OUT_JS
"""
import json
import sys

from fontTools.pens.boundsPen import BoundsPen
from fontTools.pens.recordingPen import RecordingPen
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen
from fontTools.ttLib import TTFont


def contours(recording):
    """Split a RecordingPen value into one command list per contour."""
    cur = []
    for op, args in recording:
        cur.append((op, args))
        if op in ("closePath", "endPath"):
            yield cur
            cur = []
    if cur:
        yield cur


def main(font_path, chars, out_path):
    font = TTFont(font_path)
    glyphs = font.getGlyphSet()
    cmap = font.getBestCmap()
    upem = font["head"].unitsPerEm
    flip = (1 / upem, 0, 0, -1 / upem, 0, 0)
    data = {}
    for ch in chars:
        name = cmap[ord(ch)]
        g = glyphs[name]
        rec = RecordingPen()
        g.draw(TransformPen(rec, flip))
        paths = []
        for c in contours(rec.value):
            svg = SVGPathPen(None, ntos=lambda v: f"{v:.5f}".rstrip("0").rstrip("."))
            for op, args in c:
                getattr(svg, op)(*args)
            paths.append(svg.getCommands())
        bp = BoundsPen(glyphs)
        g.draw(TransformPen(bp, flip))
        x0, y0, x1, y1 = bp.bounds
        data[ch] = {"adv": g.width / upem, "bbox": [x0, y0, x1, y1], "contours": paths}
    with open(out_path, "w", encoding="utf-8") as fh:
        fh.write("// Generated by tools/extract_glyphs.py - do not edit.\n")
        fh.write("window.GLYPHS = ")
        json.dump(data, fh, ensure_ascii=False, separators=(",", ":"))
        fh.write(";\n")
    for ch, d in data.items():
        print(ch, "contours:", len(d["contours"]), "bbox:", [round(v, 3) for v in d["bbox"]])


if __name__ == "__main__":
    main(*sys.argv[1:4])
